version: '2'
services:
    perma-app:
        image: perma
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://perma-mysql:3306/perma?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://perma-elasticsearch:9200
        ports:
            - 8080:8080
    perma-mysql:
        extends:
            file: mysql.yml
            service: perma-mysql
    perma-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: perma-elasticsearch
